# Site settings
site: Moki
title: Moki - Minimalist Jekyll Theme
keywords: ephesus, blog
description: >-
  MOKI's BLOG
lang: en-US
timezone:  Asia/Seoul
repo: https://github.com/onepase/Ephesus # site repo [optional]
google_verify:      XXX # Put your Google Verification here
google_analytics:   UA-XXXXXXXX-00 # Put your Google Analytics code
discus-identifier:  XXX

# Author settings
author:
  name: MOKI
  bio: majoring Computer Engineer @UNIST <br> KBSH 25th <br> Working on ..
  picture: assets/images/profile.jpg 
  github: JungMok-Lee # github username
  twitter: onepase # twitter username
  facebook: 이정목 # facebook username
  instagram: itxsuz_o # instagram username
  youtube: https://www.youtube.com/watch?v=WrLYmb-yxVE&list=LL&index=18g # youtube username
  linkedin: 이정목 # linkedin username
  email: gracelee1020@naver.com # email adress


# URL settings
url: "https://jungmok-lee.github.io" # Domain Name of host. [username].github.io for github pages
permalink: pretty

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links
paginate: 20
paginate_path: "/page/:num"

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false
